#!/usr/bin/env python
"""Generate LaTeX appendix tables from P7/P10 CSV artifacts."""

from __future__ import annotations

import csv
import sys
from pathlib import Path


def main() -> None:
    repo_root = Path(__file__).resolve().parents[1]
    matrix_path = repo_root / "data/results/p7_google_rl_qec_decoder_effect_matrix.csv"
    sig_path = repo_root / "data/results/p10_effect_significance.csv"
    output_path = repo_root / "paper/tables/appendix_per_condition.tex"

    # Load effect matrix
    with open(matrix_path) as f:
        matrix = list(csv.DictReader(f))

    # Load significance (filter to real_decoder_pathway scope)
    with open(sig_path) as f:
        sig_rows = [r for r in csv.DictReader(f) if r["analysis_scope"] == "real_decoder_pathway"]
    sig_by_id = {r["unit_id"]: r for r in sig_rows}

    # Sort by control_mode, basis, cycles
    matrix.sort(key=lambda r: (
        0 if r["control_mode"] == "reinforcement_learning" else 1,
        r["basis"],
        int(r["cycles"]),
    ))

    lines = []
    lines.append("% Auto-generated by scripts/38_generate_appendix_tables.py")
    lines.append("% Per-condition paired transition counts and significance for the main decoder-pathway intervention.")
    lines.append(r"\begin{table}[t]")
    lines.append(r"\centering")
    lines.append(r"\caption{Per-condition rescued/induced counts and paired significance for the main decoder-pathway intervention (correlated-matching $\rightarrow$ tesseract, both SI1000 prior) across 40 Google RL QEC real-data conditions.}")
    lines.append(r"\label{tab:appendix_per_condition}")
    lines.append(r"\small")
    lines.append(r"\begin{tabular}{lrrrrrrrc}")
    lines.append(r"\toprule")
    lines.append(r"Condition & Rescued & Induced & Discordant & $\Delta$LFR & McNemar $p$ & Holm $p$ & Holm sig. \\")
    lines.append(r"\midrule")

    current_mode = None
    for row in matrix:
        mode = row["control_mode"]
        basis = row["basis"]
        cycles = int(row["cycles"])
        rescued = int(row["rescued_failure_count"])
        induced = int(row["induced_failure_count"])
        discordant = rescued + induced
        delta = float(row["paired_delta_lfr"])

        sig = sig_by_id.get(row["workload_id"], {})
        mcnemar_p = float(sig.get("mcnemar_exact_p", "nan"))
        holm_p = float(sig.get("holm_adjusted_p", "nan"))
        holm_sig = sig.get("significant_after_holm_0_05", "False") == "True"

        # Insert group header when control_mode changes
        if mode != current_mode:
            current_mode = mode
            mode_label = "Reinforcement Learning" if mode == "reinforcement_learning" else "Traditional Calibration"
            lines.append(r"\multicolumn{8}{l}{\textbf{" + mode_label + r"}} \\")
            lines.append(r"\cmidrule(lr){1-8}")

        label = f"{basis}-basis, {cycles} cycles"
        sig_marker = r"$\star$" if holm_sig else ""
        sig_cell = f"{sig_marker}" if sig_marker else ""

        lines.append(
            f"{label} & {rescued:,} & {induced:,} & {discordant:,} & "
            f"{delta:+.4f} & {fmt_p(mcnemar_p)} & {fmt_p(holm_p)} & {sig_cell} \\\\"
        )

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")

    with open(output_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {output_path}")
    print(f"  {len(matrix)} conditions")


def fmt_p(p: float) -> str:
    if p < 1e-99:
        return "$<10^{-99}$"
    if p < 0.001:
        # Scientific notation with 2 sig figs
        exp = 0
        val = p
        while val < 1.0:
            val *= 10
            exp -= 1
        return f"${val:.2f}\\times 10^{{{exp}}}$"
    if p < 0.01:
        return f"{p:.4f}"
    return f"{p:.4f}"


if __name__ == "__main__":
    main()
