"""Stable CSV schemas for the P0 FailureOps pipeline."""

BASELINE_FIELDS = [
    "run_id",
    "circuit_id",
    "shot_id",
    "seed",
    "num_rounds",
    "num_operations",
    "data_error_rate",
    "measurement_error_rate",
    "idle_error_rate",
    "decoder_timeout_rate",
    "data_error_count",
    "measurement_error_count",
    "idle_error_count",
    "decoder_timeout",
    "decoder_delay",
    "idle_exposure",
    "error_events",
    "failure_round",
    "failure_region",
    "failure_operation",
    "failure_mode",
    "failure_pattern",
    "logical_failure",
]

INTERVENTION_FIELDS = [
    "shot_id",
    "seed",
    "intervention",
    "baseline_logical_failure",
    "intervened_logical_failure",
    "baseline_failure_round",
    "intervened_failure_round",
    "baseline_failure_mode",
    "intervened_failure_mode",
    "baseline_failure_pattern",
    "intervened_failure_pattern",
    "rescued_failure",
    "new_failure",
]

ATTRIBUTION_FIELDS = [
    "intervention",
    "num_shots",
    "baseline_logical_failure_rate",
    "intervened_logical_failure_rate",
    "absolute_delta_lfr",
    "relative_delta_lfr",
    "baseline_failure_count",
    "intervened_failure_count",
    "rescued_failure_count",
    "new_failure_count",
    "rescue_rate",
    "new_failure_rate",
    "dominant_baseline_failure_pattern",
    "dominant_intervened_failure_pattern",
]

QEC_BASELINE_FIELDS = [
    "run_id",
    "circuit_id",
    "backend",
    "code_family",
    "distance",
    "num_rounds",
    "shot_id",
    "seed",
    "data_error_rate",
    "measurement_error_rate",
    "idle_error_rate",
    "decoder_timeout_base_rate",
    "decoder_capacity",
    "decoder_backlog",
    "synchronization_slack",
    "detector_count",
    "detector_event_count",
    "detector_events",
    "observable_flip",
    "decoder_prediction",
    "qec_decoder_failure",
    "decoder_timeout",
    "decoder_delay",
    "idle_exposure",
    "runtime_idle_flip",
    "logical_failure",
    "failure_round",
    "failure_region",
    "failure_operation",
    "failure_mode",
    "failure_pattern",
]

P3_BASELINE_FIELDS = [
    "run_id",
    "workload_id",
    "circuit_id",
    "backend",
    "code_family",
    "distance",
    "num_rounds",
    "shot_id",
    "seed",
    "stress_level",
    "data_error_rate",
    "measurement_error_rate",
    "idle_error_rate",
    "decoder_timeout_base_rate",
    "detector_load_scale",
    "idle_window_scale",
    "deadline_scale",
    "decoder_workers",
    "decoder_service_rate",
    "decoder_queue_depth",
    "decoder_deadline",
    "decoder_arrival_time",
    "decoder_start_time",
    "decoder_finish_time",
    "decoder_latency",
    "decoder_deadline_miss",
    "decoder_queue_overflow",
    "decoder_timeout",
    "decoder_backlog",
    "runtime_stall_rounds",
    "idle_exposure",
    "runtime_idle_flip",
    "detector_count",
    "detector_event_count",
    "detector_events",
    "observable_flip",
    "decoder_prediction",
    "qec_decoder_failure",
    "logical_failure",
    "failure_round",
    "failure_region",
    "failure_operation",
    "failure_mode",
    "failure_pattern",
]

P3_INTERVENTION_FIELDS = [
    "run_id",
    "workload_id",
    "stress_level",
    "shot_id",
    "seed",
    "intervention",
    "intervention_class",
    "baseline_logical_failure",
    "intervened_logical_failure",
    "baseline_failure_round",
    "intervened_failure_round",
    "baseline_failure_mode",
    "intervened_failure_mode",
    "baseline_failure_pattern",
    "intervened_failure_pattern",
    "rescued_failure",
    "new_failure",
]

P3_BASELINE_COMPARISON_FIELDS = [
    "method",
    "workload_id",
    "stress_level",
    "num_groups",
    "num_shots",
    "mean_absolute_delta_lfr",
    "std_absolute_delta_lfr",
    "ci95_absolute_delta_lfr",
    "mean_rescue_rate",
    "top_intervention",
    "top_intervention_delta_lfr",
]

P3_RANK_STABILITY_FIELDS = [
    "workload_id",
    "stress_level",
    "num_groups",
    "mean_top3_overlap",
    "mean_pairwise_rank_distance",
    "top_intervention_mode",
    "top_intervention_mode_fraction",
    "ranked_interventions",
]

P3_EVAL_MATRIX_FIELDS = [
    "workload_id",
    "stress_level",
    "intervention",
    "num_groups",
    "num_shots",
    "mean_baseline_lfr",
    "mean_intervened_lfr",
    "mean_absolute_delta_lfr",
    "std_absolute_delta_lfr",
    "ci95_absolute_delta_lfr",
    "mean_rescue_rate",
    "intervention_class",
]

P4_INTERVENTION_FIELDS = [
    "pair_id",
    "run_id",
    "workload_id",
    "stress_level",
    "shot_id",
    "seed",
    "intervention",
    "intervention_class",
    "intervention_allowed_changes",
    "intervention_required_invariants",
    "baseline_record_hash",
    "intervened_record_hash",
    "baseline_event_record_hash",
    "intervened_event_record_hash",
    "pairing_valid",
    "pairing_violations",
    "baseline_logical_failure",
    "intervened_logical_failure",
    "baseline_failure_round",
    "intervened_failure_round",
    "baseline_failure_mode",
    "intervened_failure_mode",
    "baseline_failure_pattern",
    "intervened_failure_pattern",
    "rescued_failure",
    "new_failure",
]

P4_BASELINE_FIELDS = [
    *P3_BASELINE_FIELDS,
    "event_layers",
    "event_layer_hash",
    "event_record_hash",
    "record_hash",
]

P4_PAIRING_VALIDATION_FIELDS = [
    "intervention",
    "intervention_class",
    "num_pairs",
    "valid_pairs",
    "invalid_pairs",
    "violation_rate",
    "top_violations",
]

P4_PAIRED_EFFECT_FIELDS = [
    "workload_id",
    "stress_level",
    "intervention",
    "intervention_class",
    "num_pairs",
    "valid_pairs",
    "invalid_pairs",
    "baseline_failure_count",
    "intervened_failure_count",
    "rescued_failure_count",
    "induced_failure_count",
    "unchanged_failure_count",
    "unchanged_success_count",
    "net_rescue_count",
    "paired_delta_lfr",
    "paired_delta_lfr_ci_lower",
    "paired_delta_lfr_ci_upper",
    "net_rescue_rate",
    "net_rescue_rate_ci_lower",
    "net_rescue_rate_ci_upper",
    "rescue_rate_among_baseline_failures",
    "induction_rate_among_baseline_successes",
    "num_bootstrap",
    "bootstrap_seed",
]

P5_RUNTIME_TRACE_FIELDS = [
    "trace_id",
    "trace_source",
    "run_id",
    "workload_id",
    "stress_level",
    "shot_id",
    "seed",
    "decoder_arrival_time",
    "decoder_start_time",
    "decoder_finish_time",
    "decoder_latency",
    "decoder_queue_wait",
    "decoder_service_time",
    "decoder_backlog",
    "decoder_timeout",
    "decoder_deadline_miss",
    "decoder_queue_overflow",
    "runtime_stall_rounds",
    "idle_exposure",
    "runtime_idle_flip",
]

P6_MODE_SUMMARY_FIELDS = [
    "mode_id",
    "backend",
    "runtime_source",
    "event_model",
    "workloads",
    "stress_levels",
    "baseline_rows",
    "intervention_rows",
    "validation_rows",
    "effect_rows",
    "invalid_pairs",
    "max_violation_rate",
    "strongest_intervention",
    "strongest_paired_delta_lfr",
    "strongest_intervention_class",
]

P6_INTERVENTION_STABILITY_FIELDS = [
    "intervention",
    "num_modes",
    "mode_ids",
    "mean_paired_delta_lfr",
    "min_paired_delta_lfr",
    "max_paired_delta_lfr",
    "mean_net_rescue_rate",
    "top_mode",
    "top_mode_paired_delta_lfr",
]

P6_RANK_STABILITY_FIELDS = [
    "num_modes",
    "mean_top3_overlap",
    "mean_pairwise_rank_distance",
    "mode_rankings",
]

P7_BASELINE_FIELDS = [
    "run_id",
    "workload_id",
    "stress_level",
    "experiment_name",
    "basis",
    "cycles",
    "cycle_dir",
    "source_data_dir",
    "circuit_id",
    "backend",
    "code_family",
    "shot_id",
    "seed",
    "detector_count",
    "detector_event_count",
    "detector_events",
    "observable_flip",
    "decoder_pathway",
    "decoder_prediction",
    "qec_decoder_failure",
    "logical_failure",
    "failure_round",
    "failure_region",
    "failure_operation",
    "failure_mode",
    "failure_pattern",
    "event_layers",
    "event_layer_hash",
    "event_record_hash",
    "record_hash",
]

P7_DECODER_INTERVENTION_FIELDS = [
    *P4_INTERVENTION_FIELDS,
    "baseline_decoder_pathway",
    "intervened_decoder_pathway",
]

P7_SWEEP_SUMMARY_FIELDS = [
    "experiment_name",
    "code_family",
    "control_mode",
    "basis",
    "cycle_dir",
    "cycles",
    "workload_id",
    "baseline_decoder_pathway",
    "intervened_decoder_pathway",
    "num_pairs",
    "valid_pairs",
    "invalid_pairs",
    "baseline_failure_count",
    "intervened_failure_count",
    "rescued_failure_count",
    "induced_failure_count",
    "unchanged_failure_count",
    "unchanged_success_count",
    "net_rescue_count",
    "baseline_lfr",
    "intervened_lfr",
    "paired_delta_lfr",
    "net_rescue_rate",
    "rescue_rate_among_baseline_failures",
    "induction_rate_among_baseline_successes",
    "pairing_violation_rate",
    "source_data_dir",
]

P7_SWEEP_AGGREGATE_FIELDS = [
    "group_by",
    "group_value",
    "num_conditions",
    "total_pairs",
    "mean_baseline_lfr",
    "mean_intervened_lfr",
    "mean_paired_delta_lfr",
    "min_paired_delta_lfr",
    "max_paired_delta_lfr",
    "mean_net_rescue_rate",
    "strongest_condition",
    "strongest_paired_delta_lfr",
]

P7_5_FEATURE_FIELDS = [
    "experiment_name",
    "code_family",
    "control_mode",
    "basis",
    "cycles",
    "workload_id",
    "transition_class",
    "num_shots",
    "mean_detector_event_count",
    "mean_early_detector_count",
    "mean_mid_detector_count",
    "mean_late_detector_count",
    "burst_fraction",
    "mean_first_detector_fraction",
    "source_data_dir",
]

P7_5_VARIANCE_FIELDS = [
    "experiment_name",
    "code_family",
    "control_mode",
    "basis",
    "cycles",
    "workload_id",
    "num_pairs",
    "paired_delta_lfr",
    "paired_bootstrap_std",
    "unpaired_bootstrap_std",
    "std_ratio_unpaired_over_paired",
    "paired_ci_lower",
    "paired_ci_upper",
    "unpaired_ci_lower",
    "unpaired_ci_upper",
    "num_bootstrap",
    "source_data_dir",
]

P7_5_PRIOR_EFFECT_FIELDS = [
    "source_data_dir",
    "baseline_prior",
    "intervened_prior",
    *P4_PAIRED_EFFECT_FIELDS,
]

P8_DECODER_RUNTIME_TRACE_FIELDS = [
    "trace_id",
    "trace_source",
    "run_id",
    "workload_id",
    "stress_level",
    "experiment_name",
    "basis",
    "cycles",
    "cycle_dir",
    "source_data_dir",
    "decoder_pathway",
    "repeat_id",
    "batch_id",
    "batch_size",
    "shot_id",
    "seed",
    "detector_count",
    "detector_event_count",
    "decoder_arrival_time",
    "decoder_start_time",
    "decoder_finish_time",
    "decoder_latency",
    "decoder_queue_wait",
    "decoder_service_time",
    "decoder_backlog",
    "decoder_timeout",
    "decoder_deadline_miss",
    "decoder_queue_overflow",
    "runtime_stall_rounds",
    "idle_exposure",
    "runtime_idle_flip",
    "observable_flip",
    "measured_decoder_prediction",
    "stored_decoder_prediction",
    "prediction_matches_stored",
    "measured_logical_failure",
]

P8_DECODER_RUNTIME_BATCH_FIELDS = [
    "run_id",
    "workload_id",
    "stress_level",
    "experiment_name",
    "basis",
    "cycles",
    "cycle_dir",
    "source_data_dir",
    "decoder_pathway",
    "repeat_id",
    "batch_id",
    "batch_size",
    "first_shot_id",
    "last_shot_id",
    "mean_detector_event_count",
    "max_detector_event_count",
    "decode_wall_time_ns",
    "decode_wall_time_us",
    "per_shot_decode_time_us",
    "throughput_shots_per_second",
]

P8_DECODER_RUNTIME_SUMMARY_FIELDS = [
    "run_id",
    "workload_id",
    "stress_level",
    "experiment_name",
    "basis",
    "cycles",
    "cycle_dir",
    "source_data_dir",
    "decoder_pathway",
    "num_shots",
    "batch_size",
    "num_batches",
    "repeats",
    "matching_build_time_us",
    "total_decode_wall_time_us",
    "mean_per_shot_decode_time_us",
    "median_per_shot_decode_time_us",
    "p95_per_shot_decode_time_us",
    "max_per_shot_decode_time_us",
    "throughput_shots_per_second",
    "prediction_mismatch_count",
    "prediction_mismatch_rate",
    "measured_logical_failure_rate",
    "deadline_us",
    "deadline_miss_rate",
]

P9_CLAIM_TABLE_FIELDS = [
    "claim_id",
    "paper_claim",
    "evidence_source",
    "metric",
    "value",
    "interpretation",
    "limitation",
    "citation_artifact",
]

P9_REALNESS_TABLE_FIELDS = [
    "evidence_mode",
    "qec_record_source",
    "decoder_output_source",
    "runtime_source",
    "supports_claim",
    "does_not_support_claim",
    "primary_artifacts",
]

P9_PAIRING_VALIDITY_FIELDS = [
    "evidence_source",
    "num_units",
    "valid_units",
    "invalid_units",
    "violation_rate",
    "validation_note",
    "source_artifact",
]

P9_EVIDENCE_SUMMARY_FIELDS = [
    "summary_id",
    "evidence_source",
    "num_conditions",
    "num_pairs",
    "baseline_lfr",
    "intervened_lfr",
    "paired_delta_lfr",
    "rescued_failure_count",
    "induced_failure_count",
    "strongest_condition",
    "strongest_paired_delta_lfr",
    "mean_unpaired_over_paired_std_ratio",
    "p8_mean_decode_us",
    "p8_p95_decode_us",
    "p8_throughput_shots_per_second",
    "source_artifacts",
]

P10_BASELINE_COMPARISON_FIELDS = [
    "method",
    "comparison_scope",
    "ranking_target",
    "top_item",
    "top_value",
    "top3_overlap_with_failureops",
    "spearman_with_failureops",
    "mean_absolute_delta_lfr",
    "mean_uncertainty_metric",
    "interpretation",
    "limitation",
    "source_artifact",
]

P10_ROBUSTNESS_FIELDS = [
    "check_id",
    "scope",
    "num_units",
    "metric",
    "value",
    "supporting_value",
    "interpretation",
    "limitation",
    "source_artifact",
]

P10_RUNTIME_DEADLINE_INTERVENTION_FIELDS = [
    "pair_id",
    "shot_id",
    "deadline_us",
    "decoder_service_time_us",
    "deadline_miss",
    "baseline_logical_failure",
    "intervened_logical_failure",
    "rescued_failure",
    "induced_failure",
    "baseline_prediction",
    "intervened_prediction",
    "observable_flip",
]

P10_RUNTIME_DEADLINE_SUMMARY_FIELDS = [
    "deadline_us",
    "num_pairs",
    "deadline_miss_count",
    "deadline_miss_rate",
    "baseline_lfr",
    "intervened_lfr",
    "paired_delta_lfr",
    "rescued_failure_count",
    "induced_failure_count",
    "unchanged_failure_count",
    "unchanged_success_count",
    "mean_service_time_us",
    "p95_service_time_us",
    "interpretation",
    "source_artifact",
]

P10_EFFECT_SIGNIFICANCE_FIELDS = [
    "analysis_scope",
    "unit_id",
    "intervention",
    "num_pairs",
    "rescued_failure_count",
    "induced_failure_count",
    "discordant_pair_count",
    "paired_delta_lfr",
    "net_rescue_rate",
    "effect_direction",
    "mcnemar_exact_p",
    "holm_adjusted_p",
    "significant_after_holm_0_05",
    "interpretation",
    "source_artifact",
]

P10_CLAIM_AUDIT_FIELDS = [
    "claim_id",
    "claim",
    "evidence_status",
    "primary_metric",
    "observed_value",
    "pass_criterion",
    "passes",
    "limitation",
    "no_hardware_resolution",
    "source_artifact",
]

P10_EUROSYS_DIGEST_FIELDS = [
    "story_id",
    "story_section",
    "claim",
    "key_metric",
    "key_result",
    "why_it_matters",
    "scope_boundary",
    "source_artifact",
]

P10_EXTERNAL_REPLICATION_FIELDS = [
    "source_dataset",
    "dataset_family",
    "experiment_name",
    "code_family",
    "basis",
    "distance",
    "cycles",
    "center",
    "workload_id",
    "baseline_decoder_pathway",
    "intervened_decoder_pathway",
    "num_pairs",
    "baseline_failure_count",
    "intervened_failure_count",
    "rescued_failure_count",
    "induced_failure_count",
    "unchanged_failure_count",
    "unchanged_success_count",
    "net_rescue_count",
    "baseline_lfr",
    "intervened_lfr",
    "paired_delta_lfr",
    "net_rescue_rate",
    "rescue_rate_among_baseline_failures",
    "induction_rate_among_baseline_successes",
    "mean_detector_event_count",
    "source_data_dir",
]

P10_EXTERNAL_REPLICATION_AGGREGATE_FIELDS = [
    "source_dataset",
    "group_by",
    "group_value",
    "num_conditions",
    "total_pairs",
    "mean_baseline_lfr",
    "mean_intervened_lfr",
    "mean_paired_delta_lfr",
    "min_paired_delta_lfr",
    "max_paired_delta_lfr",
    "strongest_condition",
    "strongest_paired_delta_lfr",
]

P10_EXTERNAL_SANITY_FIELDS = [
    "source_dataset",
    "evidence_type",
    "analysis_scope",
    "num_units",
    "baseline_metric",
    "intervened_metric",
    "absolute_delta",
    "relative_delta",
    "interpretation",
    "failureops_compatibility",
    "source_artifact",
]
